project:
  type: website
  output-dir: docs

lang: es
website:
  title: "Ciencia de Datos con Python"
  site-url: https://christian-f-badillo.github.io/Ciencia-de-datos-con-Python-de-estadistica-descriptiva-a-redes-neuronales/
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  page-footer: 
    left: |
      Copyright {{< fa brands creative-commons >}} 2024 por Christian Francisco Badillo Hernández <br>
      Contenido con licencia {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/) 
    right: |
      Hecho con [{{< fa brands python >}}](https://www.python.org/) y [Quarto](https://quarto.org) <br>
      Código fuente disponible en [GitHub](https://github.com/Christian-F-Badillo/Ciencia-de-datos-con-Python-de-estadistica-descriptiva-a-redes-neuronales)


  repo-url: https://github.com/Christian-F-Badillo/Ciencia-de-datos-con-Python-de-estadistica-descriptiva-a-redes-neuronales
  
  repo-actions: [edit, issue]

  open-graph: 
    locale: es_MX
    site-name: Ciencia de Datos con Python
  
  sidebar:
    search: true
    style: docked
    logo: img/logo-members/Lab25_logo_2015.png
    title: "Ciencia de Datos con Python"
    subtitle: "De Estadística Descriptiva a Redes Neuronales"
    type: light
    background: primary
    border: true
    pinned: false
    collapse-level: 2
    tools: 
      - icon: github
        menu:
        - text: Source Code
          url: https://github.com/Christian-F-Badillo/Ciencia-de-datos-con-Python-de-estadistica-descriptiva-a-redes-neuronales
  
  # Contenido
    contents:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca
      
      - text: "---"

      - section: "Fundamentos de Python"
        contents: intro_python/*.qmd

      - section: "Manejo de Datos"

      - section: "Estadística con Python"
      
      - section: "Redes Neuronales"

format:
  html:
    link-external-icon: true
    
    theme:
      light: cerulean
      dark: superhero
    
    css: styles.css
    toc: true
    toc-title: "Tabla de Contenido"
    toc-depth: 3
    code-line-numbers: true
    code-fold: show
    code-copy: true
    code-overflow: scroll
    code-tools:
      source: repo
      toggle: true
      caption: "Ver código"
    code-block-border-left: warning
    code-block-bg: false
    highlight-style: github
    code-link: false

    fig-align: center

    plotly-connected: true

execute: 
  cache: true
  echo: true
  output: true
  freeze: auto
  keep-ipynb: true
  kernel: python3

